//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyak3Zh1
{
    using System;
    using System.Collections.Generic;
    
    public partial class connector
    {
        public int connId { get; set; }
        public int projectId { get; set; }
        public int workerId { get; set; }
    }
}
